### ISSUE TITLE
Would like to be able to kill java process

### ISSUE THREAD

**Issue by ctwise** [ajermakovics/jvm-mon#11]
I would like to be able to kill a java process from the monitor.

**Comment by ajermakovics** [comment]
Sounds like a nice feature. Not sure if we can kill a java process via an api but running a `kill` command should be possible. Probably just a matter of adding a key handler like this:
https://github.com/ajermakovics/jvm-mon/blob/master/src/dist/jvm-mon.js#L92

**Comment by ajermakovics** [comment]
Added in v 0.2 - press Delete/Backspace to kill a selected JVM process. It will issue a SIGTERM
