### ISSUE TITLE
Find and load tools.jar from java code

### ISSUE THREAD

**Issue by ajermakovics** [ajermakovics/jvm-mon#15]
To avoid setting `JAVA_HOME` env var before launching

Perhaps using `javax.tools.ToolProvider.getSystemToolClassLoader()`
http://docs.oracle.com/javase/7/docs/api/javax/tools/ToolProvider.html#getSystemToolClassLoader()

**Comment by janhoy** [comment]
Java 9 has no tools.jar :)

**Comment by ajermakovics** [comment]
@janhoy That... is going to be a headache:)
Haven't had the chance to dive into Java 9 so not sure how easy it would be to migrate.

**Comment by ajermakovics** [comment]
The new version is re-written in Go and no longer depends on tools.jar
https://github.com/ajermakovics/jvm-mon/releases
Works with Java 11
