### ISSUE TITLE
when start got error

### ISSUE THREAD

**Issue by peng051410** [ajermakovics/jvm-mon#20]
objc[56636]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/bin/java (0x10b6864c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_73.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x11333f4e0). One of the two will be used. Which one is undefined.

**Comment by ajermakovics** [comment]
Hi @peng051410 

Seeing the same issue but it can't be solved in jvm-mon. Unfortunately it is a bug in java and the fix has not yet been released: http://stackoverflow.com/a/43182301/1180621

**Comment by peng051410** [comment]
I got it, thank you very much!
