### ISSUE TITLE
Stack guard message, then empty screen and broken console

### ISSUE THREAD

**Issue by tomaszglinski** [ajermakovics/jvm-mon#27]
Hi, during the startup I get the "You have loaded library...." message, then my console is cleared and nothing is shown.
![image](https://user-images.githubusercontent.com/8693263/50085913-c381e600-01fb-11e9-8f4b-96f4272b30df.png)

When I CTRL-C, my console is not usable, since there is only 1 line available. On the screenshot there is an OLD line written, then Enter, then NEW written:
![image](https://user-images.githubusercontent.com/8693263/50086361-1314e180-01fd-11e9-9dc5-38cfba50f205.png)

Any ideas? I work on Windows, using Cygwin consoles managed by ConEmu 64

Possible hint: I got I working the first time! But since then never again...

**Comment by ajermakovics** [comment]
Hi,

Some users have reported issues when running jvm-mon as root. Might be worth a try to run as a normal user
