### ISSUE TITLE
Package using capsule

### ISSUE THREAD

**Issue by ajermakovics** [ajermakovics/jvm-mon#3]
To produce a single executable jar http://www.capsule.io

or maybe Packr https://github.com/libgdx/packr

**Comment by MartyIX** [comment]
https://github.com/johnrengelman/shadow is a gradle plugin and it is quite easy to setup. Just an alternative. :-)

**Comment by ajermakovics** [comment]
Thanks @MartyIX, will have a look. Wonder if it supports jars with native libraries in it

**Comment by MartyIX** [comment]
@ajermakovics I'm not sure what the precise meaning of "native libraries" is. However, I use it for my app and it packs to a jar file all dependencies (from Maven central or or the jar files I got from elsewhere).

**Comment by ajermakovics** [comment]
Tried the shadow plugin but couldn't get it to work with jvm-mon in a short time. I now realize there might be other issues because apart from the .class files jvm-mon also needs:
- jvm-mon.js file
- node_libraries/ directory
- native libraries (.so, .dll) from j2v8 jars

I couldn't find how to include node_libraries/ directory into the shadow jar. Even if I didn't, I'm not sure that j2v8 is able to load them from the classpath. I think it's designed to load files from the filesystem but I might be misunderstanding.

**Comment by MartyIX** [comment]
I see. It was just an idea :)

**Comment by ajermakovics** [comment]
New version is a single executable binary now
https://github.com/ajermakovics/jvm-mon/releases
