### ISSUE TITLE
Make available through homebrew

### ISSUE THREAD

**Issue by johanhaleby** [ajermakovics/jvm-mon#5]
Would be great if it would be possible to distribute it using homebrew

**Comment by ajermakovics** [comment]
Great idea! Have never published on homebrew before so not sure how easy it is

**Comment by johanhaleby** [comment]
I've tried to publish a project once, [kubetail](https://github.com/johanhaleby/kubetail) but it was declined :). You should probably open up a tap (which is what I'll try to do next). Maybe you can find some inspiration from the [wiki page](https://github.com/johanhaleby/kubetail/wiki/HowToRelease) I wrote, if not then I suppose one has to read the docs :/

**Comment by ctwise** [comment]
It's easy to publish on homebrew, the "recipes" are simple scripts. But... the app needs to be self-contained. You can't have scripts that have to be called from certain directories, npm installs that need to be run, etc.

**Comment by ajermakovics** [comment]
The 'self-contained' bit might be tricky. jvm-mon relies on a jdk being on the machine.

**Comment by janhoy** [comment]
I tried it out locally, and this simple formula works:
https://gist.github.com/03eea1303e5a9ff1a85dfffd96d4a674
(Download and copy to /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/jvm-mon.rb)

This is the file layout after install

    /usr/local/Cellar$ tree -L 3 jvm-mon/
    jvm-mon/
    └── 0.2
        ├── INSTALL_RECEIPT.json
        ├── bin
        │   └── jvm-mon -> ../libexec/bin/jvm-mon
        └── libexec
            ├── bin
            ├── jvm-mon.js
            ├── lib
            └── node_modules

**Comment by janhoy** [comment]
As you see, we specify java 8 as a dependency, and the node deps do not install any moving parts, so should be safe. Anyway, it works :)

**Comment by ajermakovics** [comment]
@johanhaleby That's awesome! Works like a charm. Will try to make a new release and submit a formula pr.
Cheers!

**Comment by ajermakovics** [comment]
Submitted PR https://github.com/Homebrew/homebrew-core/pull/11661
Unfortunately automatic checks failed but not quite sure why. Works locally

**Comment by ajermakovics** [comment]
Ok, the formula needs a test

**Comment by ajermakovics** [comment]
It's been merged into homebrew! Thank you @janhoy! 

`brew install jvm-mon`
