### ISSUE TITLE
Display Java processes being run by other users on a box

### ISSUE THREAD

**Issue by tom-smalls** [ajermakovics/jvm-mon#7]
I like the idea of jvm-mon, but it would be really useful if it displayed/monitored all the java processes running on a box (irrespective of user). If I run jvm-mon as root on my machine (Fedora 23) I would expect to be able to see all java processes running (they are available via jps), but this isn't the case.

**Comment by ajermakovics** [comment]
Interesting. Tried it on ubuntu but it did show jvms from normal users. Not sure what determines this... are all of them using the same jre/jdk?

That reminds me that the processes table should show the owning user.

**Comment by tom-smalls** [comment]
Using the same JVM, I do not see the same processes when running as the user that owns our various Java processes as when I am as root

**Comment by tom-smalls** [comment]
Should add I am using jdk 1.8.0_74

**Comment by ajermakovics** [comment]
Couldn't reproduce this locally but it looks like an open issue https://github.com/patric-r/jvmtop/issues/93

**Comment by tom-smalls** [comment]
I guess this comes down to a "can't fix" based on that issue you referenced (sorry not not getting back straight away)
